kind = "web"
previewPath = "/"
title = "SUPRÊME FAMILLE MUZAN AMPIROUS"
version = "1.0.0"
id = "artifacts/sfma"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 18668

[services.development]
run = "pnpm --filter @workspace/sfma run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/sfma", "run", "build" ]
publicDir = "artifacts/sfma/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "18668"
BASE_PATH = "/"
